---
name: Run RSpec Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RSpec tests
        run: bundle exec rspec spec/lib/bot_spec.rb
